<a href="https://colab.research.google.com/github/murtazaarsh7/ml_in_summers2026/blob/main/ipl_win_predict.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('/content/drive/MyDrive/IPL.csv')

/tmp/ipykernel_2201/3548107150.py:1: DtypeWarning: Columns (28,29,30,31,43,46,47,48,51) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv('/content/drive/MyDrive/IPL.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 283678 entries, 0 to 283677
Data columns (total 65 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Unnamed: 0         283678 non-null  int64
 1   match_id           283678 non-null  int64
 2   date               283678 non-null  object
 3   match_type         283678 non-null  object
 4   event_name         283678 non-null  object
 5   innings            283678 non-null  int64
 6   batting_team       283678 non-null  object
 7   bowling_team       283678 non-null  object
 8   over               283678 non-null  int64
 9   ball               283678 non-null  int64
 10  ball_no            283678 non-null  float64
 11  batter             283678 non-null  object
 12  bat_pos            283678 non-null  int64
 13  runs_batter        283678 non-null  int64
 14  balls_faced        283678 non-null  int64
 15  bowler             283678 non-null  object
 16  valid_ball         283678 non-null  int64
 17  runs_extras        283678 non-null  int64
 18  runs_total         283678 non-null  int64
 19  runs_bowler        283678 non-null  int64
 20  runs_not_boundary  283678 non-null  bool
 21  extra_type         15493 non-null   object
 22  non_striker        283678 non-null  object
 23  non_striker_pos    283678 non-null  int64
 24  wicket_kind        14106 non-null   object
 25  player_out         14106 non-null   object
 26  fielders           10245 non-null   object
 27  runs_target        136510 non-null  float64
 28  review_batter      907 non-null     object
 29  team_reviewed      907 non-null     object
 30  review_decision    907 non-null     object
 31  umpire             907 non-null     object
 32  umpires_call       283678 non-null  bool
 33  player_of_match    283678 non-null  object
 34  match_won_by       283678 non-null  object
 35  win_outcome        278954 non-null  object
 36  toss_winner        283678 non-null  object
 37  toss_decision      283678 non-null  object
 38  venue              283678 non-null  object
 39  city               283678 non-null  object
 40  day                283678 non-null  int64
 41  month              283678 non-null  int64
 42  year               283678 non-null  int64
 43  season             283678 non-null  object
 44  gender             283678 non-null  object
 45  team_type          283678 non-null  object
 46  superover_winner   3896 non-null    object
 47  result_type        4724 non-null    object
 48  method             3890 non-null    object
 49  balls_per_over     283678 non-null  int64
 50  overs              283678 non-null  int64
 51  event_match_no     283678 non-null  object
 52  stage              283678 non-null  object
 53  match_number       283678 non-null  object
 54  team_runs          283678 non-null  int64
 55  team_balls         283678 non-null  int64
 56  team_wicket        283678 non-null  int64
 57  new_batter         13593 non-null   object
 58  power_surge_start  0 non-null       float64
 59  batter_runs        283678 non-null  int64
 60  batter_balls       283678 non-null  int64
 61  bowler_wicket      283678 non-null  int64
 62  batting_partners   283678 non-null  object
 63  next_batter        13593 non-null   object
 64  striker_out        283678 non-null  bool
dtypes: bool(3), float64(3), int64(24), object(35)
memory usage: 135.0+ MB

In [4]:
df.head(5)

,Unnamed: 0,match_id,date,match_type,event_name,innings,batting_team,bowling_team,over,ball,...,team_balls,team_wicket,new_batter,power_surge_start,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out
0,141607,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,...,1,0,NaN,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
1,141608,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,...,2,0,NaN,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
2,141609,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,...,2,0,NaN,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
3,141610,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,...,3,0,NaN,NaN,0,2,0,"('BB McCullum', 'SC Ganguly')",NaN,False
4,141611,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,...,4,0,NaN,NaN,0,3,0,"('BB McCullum', 'SC Ganguly')",NaN,False

In [5]:
match_df = df.groupby(['match_id','innings'])['runs_total'].sum().reset_index()
match_df=match_df[match_df['innings']==2]

In [6]:
match_df

      match_id  innings  runs_total
1       335982        2          82
3       335983        2         207
5       335984        2         132
7       335985        2         166
9       335986        2         112
...        ...      ...         ...
2403   1527693        2         222
2405   1529264        2         159
2407   1529265        2         160
2409   1529266        2         149
2411   1529267        2         198

[1187 rows x 3 columns]

In [7]:
df = df.merge(match_df[['match_id', 'runs_total']], left_on='match_id', right_on='match_id')
df

,Unnamed: 0,match_id,date,match_type,event_name,innings,batting_team,bowling_team,over,ball,...,team_wicket,new_batter,power_surge_start,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out,runs_total_y
0,141607,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,...,0,NaN,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False,82
1,141608,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,...,0,NaN,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False,82
2,141609,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,...,0,NaN,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False,82
3,141610,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,...,0,NaN,NaN,0,2,0,"('BB McCullum', 'SC Ganguly')",NaN,False,82
4,141611,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,...,0,NaN,NaN,0,3,0,"('BB McCullum', 'SC Ganguly')",NaN,False,82
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
283156,283673,1529267,2026-04-16,T20,Indian Premier League,2,Punjab Kings,Mumbai Indians,16,1,...,3,NaN,NaN,2,2,0,"('MP Stoinis', 'P Simran Singh')",NaN,False,198
283157,283674,1529267,2026-04-16,T20,Indian Premier League,2,Punjab Kings,Mumbai Indians,16,1,...,3,NaN,NaN,2,3,0,"('MP Stoinis', 'P Simran Singh')",NaN,False,198
283158,283675,1529267,2026-04-16,T20,Indian Premier League,2,Punjab Kings,Mumbai Indians,16,2,...,3,NaN,NaN,6,4,0,"('MP Stoinis', 'P Simran Singh')",NaN,False,198
283159,283676,1529267,2026-04-16,T20,Indian Premier League,2,Punjab Kings,Mumbai Indians,16,3,...,3,NaN,NaN,6,4,0,"('MP Stoinis', 'P Simran Singh')",NaN,False,198
283160,283677,1529267,2026-04-16,T20,Indian Premier League,2,Punjab Kings,Mumbai Indians,16,3,...,3,NaN,NaN,10,5,0,"('MP Stoinis', 'P Simran Singh')",NaN,False,198

In [8]:
df['runs_total_y']

0          82
1          82
2          82
3          82
4          82
         ...
283156    198
283157    198
283158    198
283159    198
283160    198
Name: runs_total_y, Length: 283161, dtype: int64

In [9]:
df=df[df['innings']==2]

In [10]:
df

,Unnamed: 0,match_id,date,match_type,event_name,innings,batting_team,bowling_team,over,ball,...,team_wicket,new_batter,power_surge_start,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out,runs_total_y
124,141731,335982,2008-04-18,T20,Indian Premier League,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,1,...,0,NaN,NaN,1,1,0,"('R Dravid', 'W Jaffer')",NaN,False,82
125,141732,335982,2008-04-18,T20,Indian Premier League,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,2,...,0,NaN,NaN,0,0,0,"('R Dravid', 'W Jaffer')",NaN,False,82
126,141733,335982,2008-04-18,T20,Indian Premier League,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,2,...,0,NaN,NaN,0,1,0,"('R Dravid', 'W Jaffer')",NaN,False,82
127,141734,335982,2008-04-18,T20,Indian Premier League,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,3,...,0,NaN,NaN,1,2,0,"('R Dravid', 'W Jaffer')",NaN,False,82
128,141735,335982,2008-04-18,T20,Indian Premier League,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,4,...,0,NaN,NaN,2,2,0,"('R Dravid', 'W Jaffer')",NaN,False,82
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
283156,283673,1529267,2026-04-16,T20,Indian Premier League,2,Punjab Kings,Mumbai Indians,16,1,...,3,NaN,NaN,2,2,0,"('MP Stoinis', 'P Simran Singh')",NaN,False,198
283157,283674,1529267,2026-04-16,T20,Indian Premier League,2,Punjab Kings,Mumbai Indians,16,1,...,3,NaN,NaN,2,3,0,"('MP Stoinis', 'P Simran Singh')",NaN,False,198
283158,283675,1529267,2026-04-16,T20,Indian Premier League,2,Punjab Kings,Mumbai Indians,16,2,...,3,NaN,NaN,6,4,0,"('MP Stoinis', 'P Simran Singh')",NaN,False,198
283159,283676,1529267,2026-04-16,T20,Indian Premier League,2,Punjab Kings,Mumbai Indians,16,3,...,3,NaN,NaN,6,4,0,"('MP Stoinis', 'P Simran Singh')",NaN,False,198
283160,283677,1529267,2026-04-16,T20,Indian Premier League,2,Punjab Kings,Mumbai Indians,16,3,...,3,NaN,NaN,10,5,0,"('MP Stoinis', 'P Simran Singh')",NaN,False,198

In [11]:
df['batting_team'].unique()

array(['Royal Challengers Bangalore', 'Kings XI Punjab',
       'Delhi Daredevils', 'Kolkata Knight Riders', 'Rajasthan Royals',
       'Mumbai Indians', 'Chennai Super Kings', 'Deccan Chargers',
       'Pune Warriors', 'Kochi Tuskers Kerala', 'Sunrisers Hyderabad',
       'Rising Pune Supergiants', 'Gujarat Lions',
       'Rising Pune Supergiant', 'Delhi Capitals', 'Punjab Kings',
       'Gujarat Titans', 'Lucknow Super Giants',
       'Royal Challengers Bengaluru'], dtype=object)

In [12]:
teams=['Kolkata Knight Riders', 'Rajasthan Royals',
       'Mumbai Indians', 'Chennai Super Kings'
       ,'Sunrisers Hyderabad','Delhi Capitals', 'Punjab Kings', 'Lucknow Super Giants',
       'Royal Challengers Bengaluru','Gujarat Titans']

In [13]:
df['batting_team']=df['batting_team'].str.replace('Delhi Daredevils','Delhi Capitals')
df['bowling_team']=df['bowling_team'].str.replace('Delhi Daredevils','Delhi Capitals')

df['batting_team']=df['batting_team'].str.replace('Royal Challengers Bangalore','Royal Challengers Bangalore')
df['bowling_team']=df['bowling_team'].str.replace('Royal Challengers Bangalore','Royal Challengers Bengaluru')

df['batting_team']=df['batting_team'].str.replace('Kings XI Punjab','Punjab Kings')
df['bowling_team']=df['bowling_team'].str.replace('Kings XI Punjab','Punjab Kings')

/tmp/ipykernel_2201/2805345112.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['batting_team']=df['batting_team'].str.replace('Delhi Daredevils','Delhi Capitals')
/tmp/ipykernel_2201/2805345112.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['bowling_team']=df['bowling_team'].str.replace('Delhi Daredevils','Delhi Capitals')
/tmp/ipykernel_2201/2805345112.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['batting_team']=df['batting_team'].str.replace('Royal Challengers Bangalore','Royal Challengers Bangalore')
/tmp/ipykernel_2201/2805345112.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['bowling_team']=df['bowling_team'].str.replace('Royal Challengers Bangalore','Royal Challengers Bengaluru')
/tmp/ipykernel_2201/2805345112.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['batting_team']=df['batting_team'].str.replace('Kings XI Punjab','Punjab Kings')
/tmp/ipykernel_2201/2805345112.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['bowling_team']=df['bowling_team'].str.replace('Kings XI Punjab','Punjab Kings')

In [14]:
df=df[df['batting_team'].isin(teams)]
df=df[df['bowling_team'].isin(teams)]

In [15]:
df.shape

(103668, 66)

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 103668 entries, 349 to 283160
Data columns (total 66 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Unnamed: 0         103668 non-null  int64
 1   match_id           103668 non-null  int64
 2   date               103668 non-null  object
 3   match_type         103668 non-null  object
 4   event_name         103668 non-null  object
 5   innings            103668 non-null  int64
 6   batting_team       103668 non-null  object
 7   bowling_team       103668 non-null  object
 8   over               103668 non-null  int64
 9   ball               103668 non-null  int64
 10  ball_no            103668 non-null  float64
 11  batter             103668 non-null  object
 12  bat_pos            103668 non-null  int64
 13  runs_batter        103668 non-null  int64
 14  balls_faced        103668 non-null  int64
 15  bowler             103668 non-null  object
 16  valid_ball         103668 non-null  int64
 17  runs_extras        103668 non-null  int64
 18  runs_total_x       103668 non-null  int64
 19  runs_bowler        103668 non-null  int64
 20  runs_not_boundary  103668 non-null  bool
 21  extra_type         5636 non-null    object
 22  non_striker        103668 non-null  object
 23  non_striker_pos    103668 non-null  int64
 24  wicket_kind        5138 non-null    object
 25  player_out         5138 non-null    object
 26  fielders           3703 non-null    object
 27  runs_target        103668 non-null  float64
 28  review_batter      458 non-null     object
 29  team_reviewed      458 non-null     object
 30  review_decision    458 non-null     object
 31  umpire             458 non-null     object
 32  umpires_call       103668 non-null  bool
 33  player_of_match    103668 non-null  object
 34  match_won_by       103668 non-null  object
 35  win_outcome        102022 non-null  object
 36  toss_winner        103668 non-null  object
 37  toss_decision      103668 non-null  object
 38  venue              103668 non-null  object
 39  city               103668 non-null  object
 40  day                103668 non-null  int64
 41  month              103668 non-null  int64
 42  year               103668 non-null  int64
 43  season             103668 non-null  object
 44  gender             103668 non-null  object
 45  team_type          103668 non-null  object
 46  superover_winner   1619 non-null    object
 47  result_type        1646 non-null    object
 48  method             1092 non-null    object
 49  balls_per_over     103668 non-null  int64
 50  overs              103668 non-null  int64
 51  event_match_no     103668 non-null  object
 52  stage              103668 non-null  object
 53  match_number       103668 non-null  object
 54  team_runs          103668 non-null  int64
 55  team_balls         103668 non-null  int64
 56  team_wicket        103668 non-null  int64
 57  new_batter         4987 non-null    object
 58  power_surge_start  0 non-null       float64
 59  batter_runs        103668 non-null  int64
 60  batter_balls       103668 non-null  int64
 61  bowler_wicket      103668 non-null  int64
 62  batting_partners   103668 non-null  object
 63  next_batter        4987 non-null    object
 64  striker_out        103668 non-null  bool
 65  runs_total_y       103668 non-null  int64
dtypes: bool(3), float64(3), int64(25), object(35)
memory usage: 50.9+ MB

In [17]:
df.drop_duplicates(inplace=True)

In [18]:
new_df=df[['match_id','batting_team','bowling_team','city','over','ball','team_wicket','runs_total_x','runs_total_y','team_wicket','batting_partners','team_runs','innings','match_won_by']]

In [19]:
new_df

,match_id,batting_team,bowling_team,city,over,ball,team_wicket,runs_total_x,runs_total_y,team_wicket,batting_partners,team_runs,innings,match_won_by
349,335983,Punjab Kings,Chennai Super Kings,Chandigarh,0,1,0,4,207,0,"('JR Hopes', 'K Goel')",4,2,Chennai Super Kings
350,335983,Punjab Kings,Chennai Super Kings,Chandigarh,0,2,0,0,207,0,"('JR Hopes', 'K Goel')",4,2,Chennai Super Kings
351,335983,Punjab Kings,Chennai Super Kings,Chandigarh,0,3,0,0,207,0,"('JR Hopes', 'K Goel')",4,2,Chennai Super Kings
352,335983,Punjab Kings,Chennai Super Kings,Chandigarh,0,4,0,1,207,0,"('JR Hopes', 'K Goel')",5,2,Chennai Super Kings
353,335983,Punjab Kings,Chennai Super Kings,Chandigarh,0,5,0,0,207,0,"('JR Hopes', 'K Goel')",5,2,Chennai Super Kings
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
283156,1529267,Punjab Kings,Mumbai Indians,Mumbai,16,1,3,1,198,3,"('MP Stoinis', 'P Simran Singh')",189,2,Punjab Kings
283157,1529267,Punjab Kings,Mumbai Indians,Mumbai,16,1,3,0,198,3,"('MP Stoinis', 'P Simran Singh')",189,2,Punjab Kings
283158,1529267,Punjab Kings,Mumbai Indians,Mumbai,16,2,3,4,198,3,"('MP Stoinis', 'P Simran Singh')",193,2,Punjab Kings
283159,1529267,Punjab Kings,Mumbai Indians,Mumbai,16,3,3,1,198,3,"('MP Stoinis', 'P Simran Singh')",194,2,Punjab Kings
283160,1529267,Punjab Kings,Mumbai Indians,Mumbai,16,3,3,4,198,3,"('MP Stoinis', 'P Simran Singh')",198,2,Punjab Kings

In [20]:
new_df['current_score']=new_df.groupby('match_id')['runs_total_x'].cumsum()

/tmp/ipykernel_2201/1713170625.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['current_score']=new_df.groupby('match_id')['runs_total_x'].cumsum()

In [21]:
new_df['runs_left']=new_df['runs_total_y']-new_df['current_score']+1

/tmp/ipykernel_2201/27376731.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['runs_left']=new_df['runs_total_y']-new_df['current_score']+1

In [22]:
new_df['balls_left']=120-(new_df['over']*6+new_df['ball'])

/tmp/ipykernel_2201/3673814706.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['balls_left']=120-(new_df['over']*6+new_df['ball'])

In [23]:
new_df

,match_id,batting_team,bowling_team,city,over,ball,team_wicket,runs_total_x,runs_total_y,team_wicket,batting_partners,team_runs,innings,match_won_by,current_score,runs_left,balls_left
349,335983,Punjab Kings,Chennai Super Kings,Chandigarh,0,1,0,4,207,0,"('JR Hopes', 'K Goel')",4,2,Chennai Super Kings,4,204,119
350,335983,Punjab Kings,Chennai Super Kings,Chandigarh,0,2,0,0,207,0,"('JR Hopes', 'K Goel')",4,2,Chennai Super Kings,4,204,118
351,335983,Punjab Kings,Chennai Super Kings,Chandigarh,0,3,0,0,207,0,"('JR Hopes', 'K Goel')",4,2,Chennai Super Kings,4,204,117
352,335983,Punjab Kings,Chennai Super Kings,Chandigarh,0,4,0,1,207,0,"('JR Hopes', 'K Goel')",5,2,Chennai Super Kings,5,203,116
353,335983,Punjab Kings,Chennai Super Kings,Chandigarh,0,5,0,0,207,0,"('JR Hopes', 'K Goel')",5,2,Chennai Super Kings,5,203,115
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
283156,1529267,Punjab Kings,Mumbai Indians,Mumbai,16,1,3,1,198,3,"('MP Stoinis', 'P Simran Singh')",189,2,Punjab Kings,189,10,23
283157,1529267,Punjab Kings,Mumbai Indians,Mumbai,16,1,3,0,198,3,"('MP Stoinis', 'P Simran Singh')",189,2,Punjab Kings,189,10,23
283158,1529267,Punjab Kings,Mumbai Indians,Mumbai,16,2,3,4,198,3,"('MP Stoinis', 'P Simran Singh')",193,2,Punjab Kings,193,6,22
283159,1529267,Punjab Kings,Mumbai Indians,Mumbai,16,3,3,1,198,3,"('MP Stoinis', 'P Simran Singh')",194,2,Punjab Kings,194,5,21
283160,1529267,Punjab Kings,Mumbai Indians,Mumbai,16,3,3,4,198,3,"('MP Stoinis', 'P Simran Singh')",198,2,Punjab Kings,198,1,21

In [24]:
new_df['wickets_left']=10-df['team_wicket']

/tmp/ipykernel_2201/4261911529.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['wickets_left']=10-df['team_wicket']

In [25]:
new_df

,match_id,batting_team,bowling_team,city,over,ball,team_wicket,runs_total_x,runs_total_y,team_wicket,batting_partners,team_runs,innings,match_won_by,current_score,runs_left,balls_left,wickets_left
349,335983,Punjab Kings,Chennai Super Kings,Chandigarh,0,1,0,4,207,0,"('JR Hopes', 'K Goel')",4,2,Chennai Super Kings,4,204,119,10
350,335983,Punjab Kings,Chennai Super Kings,Chandigarh,0,2,0,0,207,0,"('JR Hopes', 'K Goel')",4,2,Chennai Super Kings,4,204,118,10
351,335983,Punjab Kings,Chennai Super Kings,Chandigarh,0,3,0,0,207,0,"('JR Hopes', 'K Goel')",4,2,Chennai Super Kings,4,204,117,10
352,335983,Punjab Kings,Chennai Super Kings,Chandigarh,0,4,0,1,207,0,"('JR Hopes', 'K Goel')",5,2,Chennai Super Kings,5,203,116,10
353,335983,Punjab Kings,Chennai Super Kings,Chandigarh,0,5,0,0,207,0,"('JR Hopes', 'K Goel')",5,2,Chennai Super Kings,5,203,115,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
283156,1529267,Punjab Kings,Mumbai Indians,Mumbai,16,1,3,1,198,3,"('MP Stoinis', 'P Simran Singh')",189,2,Punjab Kings,189,10,23,7
283157,1529267,Punjab Kings,Mumbai Indians,Mumbai,16,1,3,0,198,3,"('MP Stoinis', 'P Simran Singh')",189,2,Punjab Kings,189,10,23,7
283158,1529267,Punjab Kings,Mumbai Indians,Mumbai,16,2,3,4,198,3,"('MP Stoinis', 'P Simran Singh')",193,2,Punjab Kings,193,6,22,7
283159,1529267,Punjab Kings,Mumbai Indians,Mumbai,16,3,3,1,198,3,"('MP Stoinis', 'P Simran Singh')",194,2,Punjab Kings,194,5,21,7
283160,1529267,Punjab Kings,Mumbai Indians,Mumbai,16,3,3,4,198,3,"('MP Stoinis', 'P Simran Singh')",198,2,Punjab Kings,198,1,21,7

In [26]:
new_df['crr']=new_df['current_score']*6/(120-new_df['balls_left'])

/tmp/ipykernel_2201/2144410972.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['crr']=new_df['current_score']*6/(120-new_df['balls_left'])

In [27]:
new_df

,match_id,batting_team,bowling_team,city,over,ball,team_wicket,runs_total_x,runs_total_y,team_wicket,batting_partners,team_runs,innings,match_won_by,current_score,runs_left,balls_left,wickets_left,crr
349,335983,Punjab Kings,Chennai Super Kings,Chandigarh,0,1,0,4,207,0,"('JR Hopes', 'K Goel')",4,2,Chennai Super Kings,4,204,119,10,24.000000
350,335983,Punjab Kings,Chennai Super Kings,Chandigarh,0,2,0,0,207,0,"('JR Hopes', 'K Goel')",4,2,Chennai Super Kings,4,204,118,10,12.000000
351,335983,Punjab Kings,Chennai Super Kings,Chandigarh,0,3,0,0,207,0,"('JR Hopes', 'K Goel')",4,2,Chennai Super Kings,4,204,117,10,8.000000
352,335983,Punjab Kings,Chennai Super Kings,Chandigarh,0,4,0,1,207,0,"('JR Hopes', 'K Goel')",5,2,Chennai Super Kings,5,203,116,10,7.500000
353,335983,Punjab Kings,Chennai Super Kings,Chandigarh,0,5,0,0,207,0,"('JR Hopes', 'K Goel')",5,2,Chennai Super Kings,5,203,115,10,6.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
283156,1529267,Punjab Kings,Mumbai Indians,Mumbai,16,1,3,1,198,3,"('MP Stoinis', 'P Simran Singh')",189,2,Punjab Kings,189,10,23,7,11.690722
283157,1529267,Punjab Kings,Mumbai Indians,Mumbai,16,1,3,0,198,3,"('MP Stoinis', 'P Simran Singh')",189,2,Punjab Kings,189,10,23,7,11.690722
283158,1529267,Punjab Kings,Mumbai Indians,Mumbai,16,2,3,4,198,3,"('MP Stoinis', 'P Simran Singh')",193,2,Punjab Kings,193,6,22,7,11.816327
283159,1529267,Punjab Kings,Mumbai Indians,Mumbai,16,3,3,1,198,3,"('MP Stoinis', 'P Simran Singh')",194,2,Punjab Kings,194,5,21,7,11.757576
283160,1529267,Punjab Kings,Mumbai Indians,Mumbai,16,3,3,4,198,3,"('MP Stoinis', 'P Simran Singh')",198,2,Punjab Kings,198,1,21,7,12.000000

In [28]:
new_df['rrr']=(new_df['runs_left']*6)/new_df['balls_left']

/tmp/ipykernel_2201/4153337117.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['rrr']=(new_df['runs_left']*6)/new_df['balls_left']

In [29]:
new_df

,match_id,batting_team,bowling_team,city,over,ball,team_wicket,runs_total_x,runs_total_y,team_wicket,batting_partners,team_runs,innings,match_won_by,current_score,runs_left,balls_left,wickets_left,crr,rrr
349,335983,Punjab Kings,Chennai Super Kings,Chandigarh,0,1,0,4,207,0,"('JR Hopes', 'K Goel')",4,2,Chennai Super Kings,4,204,119,10,24.000000,10.285714
350,335983,Punjab Kings,Chennai Super Kings,Chandigarh,0,2,0,0,207,0,"('JR Hopes', 'K Goel')",4,2,Chennai Super Kings,4,204,118,10,12.000000,10.372881
351,335983,Punjab Kings,Chennai Super Kings,Chandigarh,0,3,0,0,207,0,"('JR Hopes', 'K Goel')",4,2,Chennai Super Kings,4,204,117,10,8.000000,10.461538
352,335983,Punjab Kings,Chennai Super Kings,Chandigarh,0,4,0,1,207,0,"('JR Hopes', 'K Goel')",5,2,Chennai Super Kings,5,203,116,10,7.500000,10.500000
353,335983,Punjab Kings,Chennai Super Kings,Chandigarh,0,5,0,0,207,0,"('JR Hopes', 'K Goel')",5,2,Chennai Super Kings,5,203,115,10,6.000000,10.591304
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
283156,1529267,Punjab Kings,Mumbai Indians,Mumbai,16,1,3,1,198,3,"('MP Stoinis', 'P Simran Singh')",189,2,Punjab Kings,189,10,23,7,11.690722,2.608696
283157,1529267,Punjab Kings,Mumbai Indians,Mumbai,16,1,3,0,198,3,"('MP Stoinis', 'P Simran Singh')",189,2,Punjab Kings,189,10,23,7,11.690722,2.608696
283158,1529267,Punjab Kings,Mumbai Indians,Mumbai,16,2,3,4,198,3,"('MP Stoinis', 'P Simran Singh')",193,2,Punjab Kings,193,6,22,7,11.816327,1.636364
283159,1529267,Punjab Kings,Mumbai Indians,Mumbai,16,3,3,1,198,3,"('MP Stoinis', 'P Simran Singh')",194,2,Punjab Kings,194,5,21,7,11.757576,1.428571
283160,1529267,Punjab Kings,Mumbai Indians,Mumbai,16,3,3,4,198,3,"('MP Stoinis', 'P Simran Singh')",198,2,Punjab Kings,198,1,21,7,12.000000,0.285714

In [30]:
def result(row):
  return 1 if row['batting_team']==row['match_won_by'] else 0

In [31]:
new_df['result']=new_df.apply(result,axis=1)

/tmp/ipykernel_2201/1966834115.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['result']=new_df.apply(result,axis=1)

In [32]:
new_df=new_df[['batting_team','bowling_team','city','runs_left','balls_left','wickets_left','runs_total_y','crr','rrr','result']]

In [33]:
new_df

,batting_team,bowling_team,city,runs_left,balls_left,wickets_left,runs_total_y,crr,rrr,result
349,Punjab Kings,Chennai Super Kings,Chandigarh,204,119,10,207,24.000000,10.285714,0
350,Punjab Kings,Chennai Super Kings,Chandigarh,204,118,10,207,12.000000,10.372881,0
351,Punjab Kings,Chennai Super Kings,Chandigarh,204,117,10,207,8.000000,10.461538,0
352,Punjab Kings,Chennai Super Kings,Chandigarh,203,116,10,207,7.500000,10.500000,0
353,Punjab Kings,Chennai Super Kings,Chandigarh,203,115,10,207,6.000000,10.591304,0
...,...,...,...,...,...,...,...,...,...,...
283156,Punjab Kings,Mumbai Indians,Mumbai,10,23,7,198,11.690722,2.608696,1
283157,Punjab Kings,Mumbai Indians,Mumbai,10,23,7,198,11.690722,2.608696,1
283158,Punjab Kings,Mumbai Indians,Mumbai,6,22,7,198,11.816327,1.636364,1
283159,Punjab Kings,Mumbai Indians,Mumbai,5,21,7,198,11.757576,1.428571,1
283160,Punjab Kings,Mumbai Indians,Mumbai,1,21,7,198,12.000000,0.285714,1

In [34]:
new_df=new_df.sample(new_df.shape[0])

In [35]:
new_df.sample()

,batting_team,bowling_team,city,runs_left,balls_left,wickets_left,runs_total_y,crr,rrr,result
222970,Lucknow Super Giants,Rajasthan Royals,Mumbai,136,104,8,154,7.125,7.846154,0

In [46]:
new_df.isnull().sum()

batting_team    0
bowling_team    0
city            0
runs_left       0
balls_left      0
wickets_left    0
runs_total_y    0
crr             0
rrr             0
result          0
dtype: int64

In [55]:
new_df=new_df[new_df['balls_left']!=0]

In [68]:
from sklearn.model_selection import train_test_split

In [69]:
x=new_df.iloc[:,:-1]
y=new_df.iloc[:,-1]
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

In [70]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [72]:

trf=ColumnTransformer([
    ('trf',OneHotEncoder(sparse_output=False,drop='first'),['batting_team','bowling_team','city'])
],remainder='passthrough')

In [73]:

trf

ColumnTransformer(remainder='passthrough',
                  transformers=[('trf',
                                 OneHotEncoder(drop='first',
                                               sparse_output=False),
                                 ['batting_team', 'bowling_team', 'city'])])

In [74]:
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline

In [75]:

pipe=Pipeline(steps=[
    ('step1',trf),
    ('step2',LogisticRegression(solver='liblinear'))]
)

In [76]:
pipe.fit(x_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/compose/_column_transformer.py:1667: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

Pipeline(steps=[('step1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('trf',
                                                  OneHotEncoder(drop='first',
                                                                sparse_output=False),
                                                  ['batting_team',
                                                   'bowling_team', 'city'])])),
                ('step2', LogisticRegression(solver='liblinear'))])

In [77]:
from sklearn.metrics import accuracy_score

In [78]:
y_pred=pipe.predict(x_test)

In [79]:
accuracy_score(y_test,y_pred)

0.7389410512051108